# -*- coding: utf-8 -*-
"""Hw1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1X3E5O-BwJhFUgQq6AczpKLQ0HAXClQKV
"""

listTek = [1,3,5,7,9]
listCift = [0,2,4,6,8]
squares = []

listTek.extend(listCift)


for i in listTek:
  squares.append(i**2)
print(squares)