# -*- coding: utf-8 -*-
"""Hw2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1uwcauZCctBro3PANWFsPP2K5T1ztTSD-
"""

Kisi1 = {"Mezuniyet":"ÖnLisans","NotDurumu":2.5,"Mesleği":"Yazılımcı"}
Kisi2 = {"Mezuniyet":"YüksekLisans","NotDurumu":3.2,"Mesleği":"Yazılımcı"}
Kisi3 = {"Mezuniyet":"ÖnLisans","NotDurumu":4,"Mesleği":"Yazılımcı"}
Kisi4 = {"Mezuniyet":"ÖnLisans","NotDurumu":3.5,"Mesleği":"Yazılımcı"}
Kisi5 = {"Mezuniyet":"YüksekLisans","NotDurumu":3.8,"Mesleği":"Yazılımcı"}

for i in Kisi1:
  leg1 = Kisi1[i]
  leg2 = Kisi2[i]
  leg3 = Kisi3[i]
  leg4 = Kisi4[i]
  leg5 = Kisi5[i]
  print("Kisi 1 : " + str(i) + " = " + str(leg1) +".")
  print("Kisi 2 : " +str(i) + " = " + str(leg2) +".")
  print("Kisi 3 : " +str(i) + " = " + str(leg3) +".")
  print("Kisi 4 : " +str(i) + " = " + str(leg4) +".")
  print("Kisi 5 : " +str(i) + " = " + str(leg5) +".")